### ISSUE TITLE
Loading too long for players with bad network.

### ISSUE THREAD

**Issue by joe-vettek** [Flemmli97/TenshiLib#11]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

43.1.25

### Mod version

1.6.13

### Description

I'm in an area where patreon isn't freely accessible, and Tenshilib's timeout threshold is way too high at 120 seconds. This picture clearly shows the problem.
![$}I EOG63P2EIM3QJD29_IR](https://user-images.githubusercontent.com/82761814/204095888-91625acd-34a7-41a3-9f8c-6fd65227aa7b.png)

### Steps to reproduce

1. add the mod and start the server in bad network.

### Logs

https://gist.github.com/joe-vettek/a233bdd2a881d351d0d20a00d7e23129

**Comment by joe-vettek** [comment]
For comparison, this is when the network is unobstructed.
https://gist.github.com/joe-vettek/d3e3b3de07456e6e525ae766382dc27f

**Comment by Flemmli97** [comment]
1. the data is obtained via a different thread and shouldn't affect the main game in anyway
2. also the data isnt even obtained from patreon but from a github file and thus the issue lies probably somewhere else

also from the log there is nothing thats saying this mod is locking up the game. yes the data is failing to load but thats it

**Comment by joe-vettek** [comment]
I have checked the code to find the problem, and that's so strange. Github is also not accessible in my country in anytime. But the asynchronous code should deal with the network problem.
 So now the reason I insist on that the problem is casued by the Tenshilib mod is that the more two minutes loading time appear after I only add your two mod(this one and InprovedMob).
Temporarily I can't get a strong evidence. I'll find it next time. So I will close the issue now .

**Comment by Flemmli97** [comment]
ok i just checked and i made an error cause getting the data is not asynchronous. but it should still not be the cause of the problem as the time when the player joins the server is way past the time where its trying to get the data since it happens as soon as the mod is loaded.

i did fix the asynchronous stuff now though
